// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import [controller]Controller from "./[controller]_controller.js"
application.register("[controller]", [controller]Controller)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
