Development:

stripe_secret_key: 'k_test_51K3Ox2EWQuERAv6dHLW6N6AbnmkB11hsjvPh5IS84udFjny02D9Mqs1Cm1xlL7VnYGhvRS3ERRCxFw6QERWshqWK00udlkUVyg'
stripe_publishable_key: 'pk_test_51K3Ox2EWQuERAv6dn3inWQ8DJWL060Qf34t87EERmS8VANYPXNfBdpQK1GnSKRA6GZAJ8m20TExoJ8tUzxLtCvaP00ClleAXLl'

production:

stripe_secret_key: 'k_test_51K3Ox2EWQuERAv6dHLW6N6AbnmkB11hsjvPh5IS84udFjny02D9Mqs1Cm1xlL7VnYGhvRS3ERRCxFw6QERWshqWK00udlkUVyg'
stripe_publishable_key: 'pk_test_51K3Ox2EWQuERAv6dn3inWQ8DJWL060Qf34t87EERmS8VANYPXNfBdpQK1GnSKRA6GZAJ8m20TExoJ8tUzxLtCvaP00ClleAXLl'
